name: pcm_sd3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.27.2
    - aiofiles==23.2.1
    - altair==5.2.0
    - annotated-types==0.6.0
    - anyio==4.3.0
    - appdirs==1.4.4
    - attrs==23.2.0
    - bitsandbytes==0.43.0
    - braceexpand==0.1.7
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.0
    - cramjam==2.8.2
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.0
    - fastapi==0.110.0
    - fastparquet==2024.2.0
    - ffmpy==0.3.2
    - filelock==3.13.1
    - fonttools==4.49.0
    - fsspec==2024.2.0
    - ftfy==6.1.3
    - gitdb==4.0.11
    - gitpython==3.1.42
    - gradio==3.48.0
    - gradio-client==0.6.1
    - grpcio==1.62.1
    - h11==0.14.0
    - httpcore==1.0.4
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - idna==3.6
    - importlib-metadata==7.0.2
    - importlib-resources==6.1.3
    - install==1.3.5
    - jinja2==3.1.3
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - lpips==0.1.4
    - markdown==3.5.2
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu12==12.1.105
    - orjson==3.9.15
    - packaging==24.0
    - pandas==2.2.1
    - peft==0.9.0
    - pillow==10.2.0
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyarrow==15.0.1
    - pydantic==2.6.3
    - pydantic-core==2.16.3
    - pydub==0.25.1
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.9
    - pytorch-fid==0.3.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - referencing==0.33.0
    - regex==2023.12.25
    - requests==2.31.0
    - rpds-py==0.18.0
    - safetensors==0.4.2
    - scipy==1.12.0
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - sentry-sdk==1.41.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - starlette==0.36.3
    - sympy==1.12
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tokenizers==0.15.2
    - toolz==0.12.1
    - torch==2.2.0
    - torchvision==0.17.0
    - tqdm==4.66.2
    - transformers==4.38.2
    - triton==2.2.0
    - typing-extensions==4.10.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - uvicorn==0.28.0
    - wandb==0.16.4
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - websockets==11.0.3
    - werkzeug==3.0.1
    - xformers==0.0.24
    - zipp==3.17.0
